name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Install Nixpacks
        run: curl -sSL https://nixpacks.com/install.sh | bash

      - name: Build image with Nixpacks
        run: ./bin/build

      - name: Run image
        run: docker run --init -d -p 20279:20279 --env API_KEY=dummy --name pptraas pptraas

      - name: Wait for container to start
        run: npx wait-on http-get://127.0.0.1:20279
        timeout-minutes: 1

      - name: Run tests
        run: node test.mjs

      - name: Percy
        run: pnpx @percy/cli upload .data/screenshots/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Print container logs
        if: always()
        run: docker logs pptraas
